function(snappin_apply_warnings target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4)
    if(SNAPPIN_STRICT_WARNINGS)
      target_compile_options(${target} PRIVATE /WX)
    endif()
    # Recommended: enable UTF-8 source
    target_compile_options(${target} PRIVATE /utf-8)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if(SNAPPIN_STRICT_WARNINGS)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
  endif()
endfunction()
